export const mockJobTemplateResponse = [
  {
    id: 7,
    type: 'job_template',
    url: '/api/controller/v2/job_templates/7/',
    related: {
      labels: '/api/controller/v2/job_templates/7/labels/',
      inventory: '/api/controller/v2/inventories/1/',
      project: '/api/controller/v2/projects/6/',
      organization: '/api/controller/v2/organizations/1/',
      credentials: '/api/controller/v2/job_templates/7/credentials/',
      jobs: '/api/controller/v2/job_templates/7/jobs/',
      schedules: '/api/controller/v2/job_templates/7/schedules/',
      activity_stream: '/api/controller/v2/job_templates/7/activity_stream/',
      launch: '/api/controller/v2/job_templates/7/launch/',
      webhook_key: '/api/controller/v2/job_templates/7/webhook_key/',
      webhook_receiver: '',
      notification_templates_started:
        '/api/controller/v2/job_templates/7/notification_templates_started/',
      notification_templates_success:
        '/api/controller/v2/job_templates/7/notification_templates_success/',
      notification_templates_error:
        '/api/controller/v2/job_templates/7/notification_templates_error/',
      access_list: '/api/controller/v2/job_templates/7/access_list/',
      survey_spec: '/api/controller/v2/job_templates/7/survey_spec/',
      object_roles: '/api/controller/v2/job_templates/7/object_roles/',
      instance_groups: '/api/controller/v2/job_templates/7/instance_groups/',
      slice_workflow_jobs:
        '/api/controller/v2/job_templates/7/slice_workflow_jobs/',
      copy: '/api/controller/v2/job_templates/7/copy/',
    },
    summary_fields: {
      organization: {
        id: 1,
        name: 'Default',
        description: '',
      },
      inventory: {
        id: 1,
        name: 'Demo Inventory',
        description: '',
        has_active_failures: false,
        total_hosts: 0,
        hosts_with_active_failures: 0,
        total_groups: 0,
        has_inventory_sources: false,
        total_inventory_sources: 0,
        inventory_sources_with_failures: 0,
        organization_id: 1,
        kind: '',
      },
      project: {
        id: 6,
        name: 'Demo Project',
        description: '',
        status: 'successful',
        scm_type: 'git',
        allow_override: false,
      },
      object_roles: {
        admin_role: {
          description: 'Can manage all aspects of the job template',
          name: 'Admin',
          id: 37,
        },
        execute_role: {
          description: 'May run the job template',
          name: 'Execute',
          id: 38,
        },
        read_role: {
          description: 'May view settings for the job template',
          name: 'Read',
          id: 39,
        },
      },
      user_capabilities: {
        edit: true,
        delete: true,
        start: true,
        schedule: true,
        copy: true,
      },
      labels: {
        count: 0,
        results: [],
      },
      recent_jobs: [],
      credentials: [
        {
          id: 1,
          name: 'Demo Credential',
          description: '',
          kind: 'ssh',
          cloud: false,
        },
      ],
    },
    created: '2025-06-02T10:39:21.487631Z',
    modified: '2025-06-02T10:39:21.487633Z',
    name: 'Demo Job Template',
    description: '',
    job_type: 'run',
    inventory: 1,
    project: 6,
    playbook: 'hello_world.yml',
    scm_branch: '',
    forks: 0,
    limit: '',
    verbosity: 0,
    extra_vars: '',
    job_tags: '',
    force_handlers: false,
    skip_tags: '',
    start_at_task: '',
    timeout: 0,
    use_fact_cache: false,
    organization: 1,
    last_job_run: null,
    last_job_failed: false,
    next_job_run: null,
    status: 'never updated',
    execution_environment: null,
    host_config_key: '',
    ask_scm_branch_on_launch: false,
    ask_diff_mode_on_launch: false,
    ask_variables_on_launch: false,
    ask_limit_on_launch: false,
    ask_tags_on_launch: false,
    ask_skip_tags_on_launch: false,
    ask_job_type_on_launch: false,
    ask_verbosity_on_launch: false,
    ask_inventory_on_launch: false,
    ask_credential_on_launch: false,
    ask_execution_environment_on_launch: false,
    ask_labels_on_launch: false,
    ask_forks_on_launch: false,
    ask_job_slice_count_on_launch: false,
    ask_timeout_on_launch: false,
    ask_instance_groups_on_launch: false,
    survey_enabled: true,
    become_enabled: false,
    diff_mode: false,
    allow_simultaneous: false,
    custom_virtualenv: null,
    job_slice_count: 1,
    webhook_service: '',
    webhook_credential: null,
    prevent_instance_group_fallback: false,
  },
];

export const mockSurveyResponse = {
  name: 'Simple Survey',
  description: 'Description of the simple survey',
  spec: [
    {
      type: 'text',
      question_name: 'example question',
      question_description: 'What is your favorite color?',
      variable: 'favorite_color',
      required: false,
      default: 'blue',
    },
  ],
};
